repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
        files: ^terraform/.*\.tf$

      - id: terraform_validate
        files: ^terraform/.*\.tf$
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color

      - id: terraform_docs
        files: ^terraform/.*
        args:
          - --hook-config=--add-to-existing-file=true

      - id: terraform_checkov
        files: ^terraform/.*
        args:
          - --args=--directory=terraform
          - --args=--config-file=.checkov.yaml
          - --args=--output=cli
          - --args=--quiet=false
          - --args=--merge-results=true
        always_run: true
        pass_filenames: false
