repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0

    # Define defaults OUTSIDE hook list
    default_hook_settings: &default_hook
      always_run: true
      pass_filenames: false

    hooks:
      - id: terraform_fmt
        <<: *default_hook
        files: ^terraform/.*\.tf$

      - id: terraform_validate
        <<: *default_hook
        files: ^terraform/.*\.tf$
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color

      - id: terraform_docs
        <<: *default_hook
        files: ^terraform/.*
        args:
          - --hook-config=--add-to-existing-file=true

      - id: terraform_checkov
        <<: *default_hook
        files: ^terraform/.*
        args:
          - --args=--directory=terraform
          - --args=--config-file=.checkov.yaml
